### ISSUE TITLE
Live webapp ends with 500

### ISSUE THREAD

**Issue by meesha7** [0xTiger/reddit-stance-classifier#1]
Upon entering any username the app crashes with 500. Sorry for not providing more info, but I don't have any.

**Comment by 0xTiger** [comment]
No worries. The cause of the issue is that the pushshift.io API endpoint this relies on to get a user's comment data: `https://api.pushshift.io/reddit/search/comment/?author=username&score=%3E0&aggs=subreddit&size=0`
is currently [disabled due to high usage](https://www.reddit.com/jm8yyt).

I don't know when this endpoint will be avaliable again, but in the meantime I shall try and make a workaround that uses the reddit API directly to gather user comment data.

**Comment by meesha7** [comment]
Ahh ok thanks for the info :)

**Comment by 0xTiger** [comment]
I'm about to merge a PR that will fix this. The predictions made will be less accurate but you should now be able to try your username on the site. :)
